apiVersion: core.oam.dev/v1beta1
kind: Application

metadata:
  name: elk-stack
  annotations:
    version: 8.7.0
    description: "Log analytics space with ELK Stack"

spec:
  components:
    # Elasticsearch component
    - name: elasticsearch
      type: webservice
      properties:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
        ports:
          - port: 9200
            expose: true
        livenessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 15
          periodSeconds: 10
        env:
          - name: xpack.security.enabled
            value: "false"
          - name: discovery.type
            value: single-node
      traits:
        - type: storage
          properties:
            emptyDir:
              - name: elasticsearch-vol
                mountPath: "/usr/share/elasticsearch/data"
        - type: napptive-ingress
          properties:
            name: elasticsearch-ingress
            port: 9200
            path: /

    # Logstash component
    - name: logstash
      type: webservice
      properties:
        image: docker.elastic.co/logstash/logstash:8.7.0
        ports:
          - port: 9600
            expose: true
        livenessProbe:
          tcpSocket:
            port: 9600
          initialDelaySeconds: 15
          periodSeconds: 10
      traits:
        - type: storage
          properties:
            emptyDir:
              - name: logstash
                mountPath: "/logstash"
        - type: napptive-ingress
          properties:
            name: logstash-ingress
            port: 9600
            path: /

    # Kibana component 
    - name: kibana
      type: webservice
      properties:
        image: docker.elastic.co/kibana/kibana:8.7.0
        ports:
          - port: 5601
            expose: true
        livenessProbe:
          tcpSocket:
            port: 5601
          initialDelaySeconds: 15
          periodSeconds: 10
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch:9200
      traits:
        - type: napptive-ingress
          properties:
            name: kibana-ingress
            port: 5601
            path: /

  policies:
    - name: healthscope-policy
      type: health
      properties:
        probeInterval: 30
        probeTimeout: 10